name: Dart Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  dart-test:
    name: Run the Dart tests
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    defaults:
      run:
        working-directory: ./apps/administration_web
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter test
